import type { CurriculumDay } from "./types";

export const STANDARD_OVERVIEW = {
  title: "7-Day Curriculum (Standard Track)",
  audience:
    "2025 tax preparation consultants in the greater Seattle area specializing in complex single-filer returns: W-2 + high RSU vesting (tech), Airbnb/STR, AFH landlord income/expenses, RSU taxation and sales, facilities + rental depreciation (cost segregation, 100% bonus depreciation under OBBBA for qualifying property placed in service after January 19, 2025), single filing status.",
  toolConstraint:
    "AI layer limited to Claude, ChatGPT, and Gemini in tandem with TurboTax Desktop (2025/2026). No other automation tools.",
  targetOutcomes: [
    "Documented TurboTax Desktop workflow for this exact income combo",
    "Started local media flywheel",
    "Initial LLM-powered agents via prompts",
    "High-touch service path toward an AI-assisted tax prep practice using only Claude/ChatGPT/Gemini",
  ],
  keyContext2025: [
    "100% bonus depreciation restored for most qualified property acquired and placed in service after Jan 19, 2025.",
    "TurboTax Desktop depreciation / Form 4562 updates for Schedule E: roughly mid–late Feb 2026.",
    "STR material participation (average stay ≤7 days) can treat activity as non-passive, allowing losses (including heavy depreciation) to offset W-2/RSU income.",
    "Common pains: accurate asset entry in TurboTax Desktop, passive vs. non-passive classification, RSU basis tracking, single-filer bracket management, multiple Schedules.",
  ],
  dailyRhythm: [
    "Morning: Video section + 2025 tax examples",
    "Midday: Hands-on TurboTax Desktop + heavy LLM prompting",
    "Afternoon/Evening: Group share — compare prompt outputs across Claude / ChatGPT / Gemini",
  ],
  requiredTools: [
    "TurboTax Desktop (latest 2025/2026 build with depreciation updates)",
    "Claude (claude.ai or API)",
    "ChatGPT (GPT-4o or equivalent)",
    "Gemini (gemini.google.com)",
  ],
};

export const STANDARD_DAYS: CurriculumDay[] = [
  {
    day: 1,
    title: "Sub-Niche Refinement & TurboTax Desktop Workflow Mapping",
    focus: "Video steps 1–5 — Narrow positioning + full manual workflow in TurboTax Desktop.",
    videoSteps: "Steps 1–5",
    dailyHours: "4–6 hours/day",
    objectives: [
      "Map every TurboTax Desktop screen for the W-2 + RSU + Airbnb/AFH + depreciation + single-filer combo.",
    ],
    exercises: [
      "Interview or review 2–3 anonymized Seattle single-filer scenarios.",
      "Manually start a sample return in TurboTax Desktop: import W-2/1099, enter RSU, set up Airbnb (Schedule C/E decision based on avg. stay), AFH rental on Schedule E, depreciation (Form 4562 with 100% bonus where eligible), single-filer optimizations.",
      "Document every screen/step. Tag mechanical steps for LLM prompting (e.g., asset list creation, eligibility checks).",
    ],
    deliverables: [
      "1-page workflow map with TurboTax Desktop screenshots + pain points (e.g., manual asset entry for bonus depreciation).",
    ],
  },
  {
    day: 2,
    title: "Media Flywheel with LLM-Assisted Content",
    focus: "Video steps 6–10 — Create content using Claude/ChatGPT/Gemini.",
    videoSteps: "Steps 6–10",
    dailyHours: "4–6 hours/day",
    objectives: [
      "Generate scroll-stopping local content on 2025 combo tax strategies.",
    ],
    exercises: [
      "Prompt the three LLMs for content ideas/hooks tailored to Seattle tech workers + AFH/Airbnb landlords.",
      "Have each model generate 3 pieces (Reels script, LinkedIn carousel, FB group post). Cross-compare quality.",
      "Post 3 pieces + set up lead magnet (e.g., “2025 TurboTax Desktop Checklist for RSU + STR + AFH Single Filers” generated by LLMs).",
    ],
    deliverables: [
      "7-day content calendar + 3 published posts.",
    ],
  },
  {
    day: 3,
    title: "Manual Execution in TurboTax Desktop",
    focus: "Video steps 11–13 — Full manual prep + detailed documentation.",
    videoSteps: "Steps 11–13",
    dailyHours: "4–6 hours/day",
    objectives: [
      "Complete one full sample return with rigorous documentation.",
    ],
    exercises: [
      "Complete one full sample return in TurboTax Desktop for the combo scenario, applying 100% bonus depreciation where qualifying.",
      "Document every single click/screen with timestamps and 2025 gotchas (bonus dep timing, material participation test for STR).",
      "Use basic LLM prompts to summarize manual steps into a checklist (first exposure to prompting).",
    ],
    deliverables: [
      "Detailed 20+ step TurboTax Desktop process document with screenshots.",
    ],
  },
  {
    day: 4,
    title: "Building LLM Agents for Mechanical Tasks",
    focus: "Video steps 14–17 — Mechanical steps → prompt-based “agents” (Claude, ChatGPT, Gemini only).",
    videoSteps: "Steps 14–17",
    dailyHours: "4–6 hours/day",
    objectives: [
      "Create repeatable prompt chains that output TurboTax Desktop-ready instructions, checklists, and calculations.",
    ],
    exercises: [
      "Select 4–6 mechanical tasks from Day 3 (e.g., bonus depreciation eligibility check, asset depreciation schedule generation, RSU basis calculator, material participation hour tracker).",
      "Craft, test, and refine prompts in all three models. Run the same prompt across Claude/ChatGPT/Gemini; compare accuracy/hallucination.",
      "Build simple orchestration by chaining prompts (e.g., Gemini → research, Claude → calculation, ChatGPT → TurboTax entry script). Add verification steps.",
      "Test on sample data; note when human judgment is still needed.",
    ],
    deliverables: [
      "Library of 10+ tested prompts + architecture diagram showing prompt flow into TurboTax Desktop.",
    ],
  },
  {
    day: 5,
    title: "Onboarding, Proof & Pricing with LLM Support",
    focus: "Video steps 18–23 — High-touch service using LLM prompts for intake and proof.",
    videoSteps: "Steps 18–23",
    dailyHours: "4–6 hours/day",
    objectives: [
      "Design onboarding and proof artifacts with LLM assistance.",
    ],
    exercises: [
      "Design onboarding form/script; use LLMs for preference-capture questions and TurboTax Desktop setup instructions.",
      "Build a proof dashboard in Google Sheets; prompt LLMs to create formulas/visuals showing “tax savings from 100% bonus dep”.",
      "Define pricing tiers; have LLMs draft client-facing explanations and case study templates.",
    ],
    deliverables: [
      "Onboarding script + sample pricing + one proof example generated with LLM help.",
    ],
  },
  {
    day: 6,
    title: "Compounding Workflows & Case Studies",
    focus: "Video steps 24–27 — Expand using LLM prompt libraries.",
    videoSteps: "Steps 24–27",
    dailyHours: "4–6 hours/day",
    objectives: [
      "Layer adjacent workflows and repurposing with cross-model refinement.",
    ],
    exercises: [
      "Map adjacent workflows (e.g., quarterly estimates, multi-year RSU planning).",
      "Prompt the three models for case study scripts and content repurposing ideas.",
      "Test compounding: feed prior-year outputs back into new prompts for improved accuracy.",
    ],
    deliverables: [
      "Expansion roadmap + 1 case study outline.",
    ],
  },
  {
    day: 7,
    title: "Scaling, Hiring & Default Layer Vision",
    focus: "Video steps 28–30 — Synthesize and plan LLM-heavy operations.",
    videoSteps: "Steps 28–30",
    dailyHours: "4–6 hours/day",
    objectives: [
      "Consolidate the week into an operational and positioning vision.",
    ],
    exercises: [
      "Create 90-day plan: integrate daily prompting into client work.",
      "Draft vision as the “Seattle Single-Filer Combo Tax Layer” powered by Claude/ChatGPT/Gemini + TurboTax Desktop.",
      "Compile all prompts into a shared playbook.",
    ],
    deliverables: [
      "90-day action plan + full vision summary + complete prompt library.",
    ],
  },
];

export const STANDARD_POST_WEEK = [
  "Use the prompt library daily when preparing returns.",
  "Continue media with LLM-generated content.",
  "Launch high-touch 2025 prep service within 2 weeks.",
  "Always cross-verify LLM outputs against IRS Pub 527, Form 4562 instructions, and TurboTax Desktop results. Never rely solely on AI for final filing.",
  "Copy the prompt library into a shared Notion/Google Doc; test every prompt across all three models; keep a “best output” version per prompt; update seasonally as TurboTax and IRS guidance evolve.",
];
